export const AUTO_MODE_RUNNING_DURATION = 30000;
export const AUTO_MODE_STOPPING_DURATION = AUTO_MODE_RUNNING_DURATION + 15000;
export const AUTO_MODE_WHOLE_DURATION =
  AUTO_MODE_RUNNING_DURATION + AUTO_MODE_STOPPING_DURATION;
