import Head from "next/head";
import styled from "styled-components";

const Container = styled.main`
  height: 100%;
`;

export default function Home() {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </Container>
  );
}
